services:
  - type: web
    name: streamlit-insurance-app
    env: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
